### ISSUE TITLE
Comments hard to read in default oh-my-zsh color pallette

### ISSUE THREAD

**Issue by qpwo** [pjmp/bropages#2]
![image](https://user-images.githubusercontent.com/10591373/107260107-c9566900-6a0b-11eb-8798-e529e89771cc.png)

Given a good portion of users will be using this with oh-my-zsh on the default color palette, could be nice if comments were a bit easier to read.

Thanks for making this.

**Comment by pombadev** [comment]
Thanks for reaching out! Since i personally don't use `oh my zsh`, do you mind providing reproduction steps?  

Btw bropages uses the excellent [bat](https://github.com/sharkdp/bat) to apply syntax highlight, so exposing a way to specify themes should not be too hard!

**Comment by pombadev** [comment]
I've added a new cli option `--theme` to specify theme supported by the underlying syntax highlighting library and changed default theme to  `OneHalfDark`, hope it helps.
Way to specify theme:
```bash
bro --theme=GitHub xclip

# list all themes
bro --list-themes
```

Will publish to crates.io shortly.

**Comment by qpwo** [comment]
Excellent, thank you so much for this wonderful tool.
