### ISSUE TITLE
installation options

### ISSUE THREAD

**Issue by AmirNaghibi** [pjmp/bropages#4]
On the GitHub README, it says:

> Currently bropages is only available through cargo

on the [bropages.org](http://bropages.org) there is another option for installation:

> gem install bropages

should add `gem install bropages` to README as well

**Comment by pombadev** [comment]
It's already mentioned in the readme that this is an unofficial rust port.

https://github.com/pjmp/bropages/blob/cfc4e70b65696189edacfebfc10928b86339fa78/README.md#L65
